// foqs.si/memecoins: podatki pridejo prek Supabase edge funkcije "market" (samo za prijavljene). Lokalna verzija uporablja /api/market.
const MARKET_URL='https://cgnihdlprjqpawvpznsw.supabase.co/functions/v1/market';
const SUPA_ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbmloZGxwcmpxcGF3dnB6bnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3ODAwODAsImV4cCI6MjEwMTM1NjA4MH0.HQgn-5op-0BYAMllyE3rbhwlLPILxvl1OVnqXau_33g';
async function marketHeaders(){const s=await (window.memecoinsSession?.()||null);return {apikey:SUPA_ANON,Authorization:'Bearer '+(s?.access_token||SUPA_ANON)};}
import {pattern,result,overview,netReturnPercent,tradeSize,parseStake} from './engine.mjs';
const $=s=>document.querySelector(s), money=x=>Number.isFinite(x)?new Intl.NumberFormat('sl-SI',{style:'currency',currency:'USD',maximumSignificantDigits:6}).format(x):'—',time=x=>new Date(x).toLocaleString('sl-SI');
let mode='live',view='market',selected=null,coins=new Map(),healthy=false,last=0,busy=false,alerts=[],announced=new Map(),step=0;
let trades=[];try{trades=JSON.parse(localStorage.getItem('solana-demo-v1')||'[]');if(!Array.isArray(trades))trades=[];}catch{};
for(const t of trades)if(!t.deletedAt&&!t.interrupted&&!t.closed)interruptTrade(t,'Ponovno odprtje strani');
function save(){try{localStorage.setItem('solana-demo-v1',JSON.stringify(trades));}catch{$('#feedback').textContent='Shranjevanje ni uspelo. Izvozi dnevnik pred zapiranjem.';}}
let stake=0.1,boardSelected=null;
try{stake=parseStake(localStorage.getItem('solana-stake-v1'))||0.1;}catch{}
function current(){return coins.get(selected);}
function fresh(c){return c&&(c.practice||(healthy&&Date.now()-c.time<75000));}
function signal(c){if(!fresh(c))return {name:'Premor',reason:'Ni svežih podatkov. Demo vstop in samodejni izstop sta ustavljena.'};if(c.liquidity<10000||!c.liquidity||!(c.volume>0))return {name:'Brez signala',reason:'Potrebujemo vsaj 10.000 USD likvidnosti in pozitiven petminutni promet.'};return pattern(c.history,c.practice?c.history.at(-1).t:Date.now());}
function draw(){let interruptedNow=false;for(const t of trades){if(!t.practice&&!t.deletedAt&&!t.closed&&!t.interrupted&&Date.now()-t.lastObserved>75000){interruptTrade(t,'Pro posamezni par več kot 75 sekund ni podatkov');interruptedNow=true;}}if(interruptedNow)save();dashboard();watching();renderBoardGraph();$('#autoPanel').hidden=mode==='practice';const c=current();$('#source').textContent=mode==='practice'?'IZMIŠLJENA VAJA':'ŽIVI POSNETKI';$('#scope').textContent=mode==='practice'?'Vaja: napreduješ ročno. Podatki so izmišljeni.':'Omejen izbor profilov DEX Screener · osvežitev na 30 s';$('#refresh').hidden=mode==='practice';$('#coins').replaceChildren();const list=[...coins.values()].sort((a,b)=>(b.created||0)-(a.created||0));if(!list.length)$('#coins').textContent='Ni razpoložljivih podatkov. Počakaj na nov prejem ali izberi Osveži.';for(const v of list){const b=document.createElement('button');b.className='coin'+(c?.id===v.id?' active':'');b.textContent=v.symbol;const s=document.createElement('small');s.textContent=v.practice?'Odboj → demo vstop → naslednja cena':`${money(v.price)} · ${fresh(v)?'opaženo '+new Date(v.time).toLocaleTimeString('sl-SI'):'podatki zastareli'}`;b.append(s);b.onclick=()=>{selected=v.id;draw();};$('#coins').append(b);}renderManual(c,'#open','#liveManualState');if(!c)return;$('#name').textContent=c.symbol;$('#address').textContent=c.practice?'Korak '+(step+1)+' · '+(step===0?'Preveri vzorec in odpri demo.':step===1?'Odpri naslednji demo za primer izgube.':'Vajo lahko začneš znova z gumbom Vodena vaja.'):'Naslov kovanca: '+c.token;$('#price').textContent=money(c.price);$('#liquidity').textContent=money(c.liquidity);$('#volume').textContent=money(c.volume);const sig=signal(c);$('#pattern').textContent=sig.name;$('#reason').textContent=sig.reason;$('#chartnote').textContent=c.practice?'Izmišljene cene v USD. Naslednji izidi so učni primeri.':`${c.history.length} cenovnih posnetkov v USD · ${c.history.length?new Date(c.history[0].t).toLocaleTimeString('sl-SI'):''} – ${c.history.length?new Date(c.history.at(-1).t).toLocaleTimeString('sl-SI'):''} · niso borzne sveče`;$('#chartnote').textContent+=sig.levels?' · Črtkano: izračunana podpora in odpor.':c.history.length<16?' · Ravni se še zbirajo; počakaj na dovolj podatkov.':' · Ravni trenutno niso na voljo: podatki ali filtri ne dovolijo izračuna.';chart(c.history,sig.levels?{support:sig.levels.support,resistance:sig.levels.resistance}:null);$('#alerts').replaceChildren();for(const a of alerts.slice(0,12)){const p=document.createElement('p');p.textContent=a;$('#alerts').append(p);}if(!alerts.length)$('#alerts').textContent='Še ni opozoril. Stran mora ostati odprta.';journal();}
function chart(h,levels,target='#chart'){
 const svg=$(target);svg.replaceChildren();const add=(tag,attrs,text)=>{const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);if(text)el.textContent=text;svg.append(el);return el;};
 const p=h.slice(-80).filter(v=>Number.isFinite(v.p)&&v.p>0);if(p.length<2){add('text',{x:25,y:110,fill:'#a7b7ca'},'Čakam na drugi cenovni posnetek …');return;}
 const refs=levels?Object.values(levels):[],min=Math.min(...p.map(v=>v.p),...refs),max=Math.max(...p.map(v=>v.p),...refs),pad=(max-min||max*.01)*.12,lo=min-pad,hi=max+pad,y=v=>185-(v-lo)/(hi-lo)*160;
 for(let i=0;i<3;i++){const value=lo+(hi-lo)*i/2,yy=y(value);add('line',{x1:110,x2:680,y1:yy,y2:yy,stroke:'#334155'});add('text',{x:3,y:yy+4,fill:'#a7b7ca','font-size':11},money(value));}
 add('text',{x:110,y:218,fill:'#a7b7ca','font-size':12},new Date(p[0].t).toLocaleTimeString('sl-SI'));add('text',{x:600,y:218,fill:'#a7b7ca','font-size':12},new Date(p.at(-1).t).toLocaleTimeString('sl-SI'));
 add('polyline',{points:p.map((v,i)=>`${110+i/(p.length-1)*570},${y(v.p)}`).join(' '),fill:'none',stroke:'#9bedcf','stroke-width':3});
 if(levels&&target==='#chart')add('text',{x:110,y:12,fill:'#a7b7ca','font-size':11},'Podpora '+money(levels.support)+' · Odpor '+money(levels.resistance));
 if(levels)for(const [key,color] of [['support','#edc687'],['resistance','#bba7f8'],['retest','#60a5fa'],['bounce','#fb923c']])if(Number.isFinite(levels[key]))add('line',{x1:110,x2:680,y1:y(levels[key]),y2:y(levels[key]),stroke:color,'stroke-dasharray':'6 5'});
}

function close(t,c,reason){t.closed=Date.now();t.exit=c.price;t.pnl=result(t.entry,t.exit,tradeSize(t));t.outcome=reason;t.exitObserved=c.time||Date.now();save();}
async function poll(){if(busy)return;busy=true;$('#refresh').disabled=true;try{const r=await fetch(MARKET_URL+'?watch='+encodeURIComponent([...new Set(trades.filter(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&!t.practice).map(t=>t.token))].join(',')),{headers:await marketHeaders(),signal:AbortSignal.timeout(20000)});if(r.status===403){window.memecoinsDenied?.();throw Error('denied');}if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data.pairs)||Date.now()-data.time>75000)throw Error();healthy=true;last=data.time;for(const p of data.pairs){const price=Number(p.priceUsd);if(!(price>0))continue;const id=p.pairAddress;const old=coins.get(id);const history=old?.history||[];if(!history.length||data.time>history.at(-1).t){history.push({p:price,t:data.time});if(history.length>160)history.shift();}const c={id,token:p.baseToken.address,symbol:p.baseToken.symbol||'Neznan',price,liquidity:p.liquidity?.usd,volume:p.volume?.m5,created:p.pairCreatedAt,time:data.time,history};coins.set(id,c);for(const t of trades.filter(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&t.id===id)){if(data.time-t.lastObserved>75000)interruptTrade(t,'Vrzel med prejemi daljša od 75 sekund');t.lastObserved=data.time;if(!t.interrupted){if(price<=t.stop)close(t,c,'Meja izgube');else if(price>=t.target)close(t,c,'Cilj');}}const s=signal(c);if(s.signal&&$("#auto").checked&&!trades.some(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&t.id===id)&&trades.filter(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&!t.practice).length<5){enter(c,s,true);}if(s.signal&&Date.now()-(announced.get(id)||0)>300000){alerts.unshift(`${time(Date.now())} · ${c.symbol} · ${s.name}`);announced.set(id,Date.now());}}if(!selected)selected=coins.keys().next().value;save();}catch{healthy=false;for(const t of trades)if(!t.deletedAt&&!t.interrupted&&!t.closed&&!t.practice)interruptTrade(t,'Napaka pri prejemu podatkov');save();}finally{busy=false;$('#refresh').disabled=false;status();draw();}}
function status(){$('#status').className='notice '+(mode==='practice'?'practice':healthy&&Date.now()-last<75000?'connected':'stopped');if(mode==='practice')$('#status').textContent='IZMIŠLJENA VAJA · najprej primer rasti, nato primer izgube. To ni napoved.';else $('#status').textContent=healthy&&Date.now()-last<75000?'Živi vir povezan · zadnji prejem '+time(last)+' · zakasnitev ponudnika ni znana.':'PREMOR · vir ni dosegljiv ali je zastarel. Živa opozorila in izstopi so ustavljeni; Počakaj na nov prejem podatkov.';}
function navigate(v,m=mode){if(m!==mode)$('#feedback').textContent='';view=v;mode=m;$('#market').hidden=v!=='market';$('#journal').hidden=v!=='journal';$('#info').hidden=v!=='info';$('#watching').hidden=v!=='watching';$('#dashboard').hidden=v!=='dashboard';for(const id of ['live','history','about','watch','overview'])$('#'+id).classList.toggle('active',id===(v==='dashboard'?'overview':v==='watching'?'watch':v==='journal'?'history':v==='info'?'about':m));status();draw();}
$('#live').onclick=()=>navigate('market','live');$('#history').onclick=()=>navigate('journal');$('#about').onclick=()=>navigate('info');$('#refresh').onclick=poll;
function enter(c,s,automatic){if((automatic&&!s.signal)||manualBlock(c)||trades.some(t=>(t.token===c.token||t.id===c.id)&&!t.deletedAt&&!t.interrupted&&!t.closed)||(automatic&&trades.some(t=>t.id===c.id&&t.signalAt===c.time))||trades.filter(t=>!t.practice&&!t.closed&&!t.interrupted&&!t.deletedAt).length>=5)return false;trades.push({key:crypto.randomUUID(),id:c.id,token:c.token,symbol:c.symbol,practice:!!c.practice,opened:Date.now(),lastObserved:c.time||Date.now(),entry:c.price,target:c.price*1.1,stop:c.price*.95,reason:automatic?s.name:"Lastna odločitev · "+s.name,ruleVersion:"1.0",automatic,signalAt:c.time||Date.now(),sizeSOL:stake,slippagePerSide:.01,feePerSide:.005,networkSOL:.00001});save();return true;}
$('#open').onclick=()=>manualEntry(current(),'#feedback');

function journal(){renderReview();renderDeleted();renderEvents();$('#rows').replaceChildren();for(const t of trades.filter(t=>!t.deletedAt&&!t.interrupted).reverse()){const tr=document.createElement('tr');const vals=[`${t.symbol} · ${t.practice?'VAJA':'ŽIVI POSNETKI'} · vložek ${tradeSize(t).toLocaleString('sl-SI')} SOL`,`${time(t.opened)} · ${t.reason} · ${t.ruleVersion||'1.0'} · ${t.automatic?'samodejno':'ročno'}${t.closed?' → '+time(t.closed):''}`,`${money(t.entry)} → ${t.closed?money(t.exit):'—'}`,t.closed?`${t.interrupted?'PO VRZELI · ':''}${t.outcome} · ${signed(t.pnl)} SOL · ${returnText(t)}`:t.interrupted?'Prekinjeno · izid med vrzeljo neznan':'Odprto'];for(const [i,v] of vals.entries()){const td=document.createElement('td');td.textContent=v;if(i===3&&t.closed)td.className=tone(t.pnl);tr.append(td);}const td=document.createElement('td');if(!t.deletedAt&&!t.interrupted&&!t.closed&&!t.practice){const b=document.createElement('button');b.textContent=t.interrupted?'Preglej prekinitev':'Preglej / zapri';b.onclick=()=>reviewTrade(t.key);td.append(b);}const manage=document.createElement('button');manage.textContent='Uredi zapis';manage.onclick=()=>reviewTrade(t.key);td.append(manage);tr.append(td);$('#rows').append(tr);}if(!trades.some(t=>!t.deletedAt&&!t.interrupted))$('#rows').textContent='Še ni demo poslov.';$('#totals').textContent=['ŽIVI POSNETKI','VAJA'].map((label,i)=>`${label}: ${trades.filter(t=>!t.deletedAt&&!t.interrupted&&t.closed&&!!t.practice===!!i).reduce((s,t)=>s+t.pnl,0).toFixed(6)} SOL neto`).join(' · ');const closed=trades.filter(t=>!t.deletedAt&&!t.interrupted&&t.closed&&!t.practice).sort((a,b)=>a.closed-b.closed),win=closed.filter(t=>t.pnl>0),loss=closed.filter(t=>t.pnl<0);let balance=0,peak=0,dd=0;for(const t of closed){balance+=t.pnl;peak=Math.max(peak,balance);dd=Math.max(dd,peak-balance);}const avg=a=>a.length?(a.reduce((s,t)=>s+t.pnl,0)/a.length).toFixed(6):'—';$('#stats').textContent=`Živi demo: ${closed.length} zaključenih · povprečni dobitek ${avg(win)} SOL · povprečna izguba ${avg(loss)} SOL · povprečni neto posel ${avg(closed)} SOL · največji padec zaključenega stanja ${dd.toFixed(6)} SOL. Odprte izgube niso vključene v ta padec. Začetno virtualno stanje za to metriko: 0 SOL; brez omejenega demo proračuna. Učenje pravil še ni izvedeno.`;}
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),assumptions:'SOL/USD nespremenjen; cene opaženih posnetkov, ne zagotovljena izvršitev.',trades},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='demo-dnevnik.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
try{const saved=localStorage.getItem('solana-auto-v1');$('#auto').checked=saved==='on';$('#autoSaved').textContent=saved===null?'Izbira še ni shranjena. Stara različica vklopa ni pomnila; po želji ga izberi enkrat.':'Naložena shranjena izbira v tem brskalniku.';}catch{$('#auto').checked=false;$('#autoSaved').textContent='Shranjevanje ni dosegljivo. Izbira se po osvežitvi morda ne bo ohranila.';}
$('#autoState').textContent=$('#auto').checked?'VKLJUČENI':'IZKLJUČENI';
poll();setInterval(poll,30000);setInterval(()=>{status();if(mode==='live')draw();},5000);

$('#auto').onchange=()=>{try{const value=$('#auto').checked?'on':'off';localStorage.setItem('solana-auto-v1',value);if(localStorage.getItem('solana-auto-v1')!==value)throw Error();$('#autoSaved').textContent='Izbira shranjena: '+(value==='on'?'vključeno':'izključeno')+'. Ostane po osvežitvi v tem brskalniku.';}catch{$('#autoSaved').textContent='Izbire ni bilo mogoče shraniti. Velja samo v tem odprtem zavihku.';}$('#autoState').textContent=$('#auto').checked?'VKLJUČENI':'IZKLJUČENI';watching();};

$('#watch').onclick=()=>navigate('watching','live');
let watchSignature="",showAllColumns=false;
function watching(){
 const signature=JSON.stringify([[...coins.values()].map(c=>[c.id,c.time,fresh(c)]),healthy,showAllColumns,$('#boardFilter').value,$('#auto').checked,trades.map(t=>[t.key,t.closed,t.interrupted,t.signalAt])]);if(signature===watchSignature)return;watchSignature=signature;
 const host=$('#watchCards');const top=$('#watchTop');const expanded=new Set([...document.querySelectorAll('#watchCards details[open], #watchTop details[open]')].map(d=>d.dataset.id));host.replaceChildren();top.replaceChildren();
 $('#watchStatus').textContent=`Posodobitev pogleda: ${time(Date.now())}. Zadnji prejem vira: ${last?time(last):'še čakamo'}. Samodejni demo vstopi: ${$('#auto').checked?'vključeni':'izključeni'}.`;
 if(!coins.size){$('#watchEmpty').textContent='Še ni kandidatov. Počakaj na povezavo .';host.textContent='Še ni kandidatov. Vir morda še nalaga podatke ali ni dosegljiv. Poskusi Živi izbor → Osveži .';return;}
 const ranked=[...coins.values()].map(c=>({c,...cardState(c)})).sort((a,b)=>b.rank-a.rank||a.c.id.localeCompare(b.c.id));const filtered=ranked.filter(x=>$('#boardFilter').value!=='fresh'||fresh(x.c));const columns=new Map();const chosen=[];for(const title of ['Zbiranje podatkov','Čakanje na vstop','Brez signala','Demo odprt']){const items=filtered.filter(x=>boardColumn(x)===title);const col=document.createElement('section');col.className='boardColumn';const h=document.createElement('h3');h.textContent=title+' · '+items.length;col.append(h);if(!items.length){const p=document.createElement('p');p.className='muted';p.textContent='Trenutno ni kovancev.';col.append(p);}columns.set(title,col);top.append(col);chosen.push(...items.slice(0,showAllColumns?items.length:3));}$('#watchEmpty').textContent=ranked.some(x=>x.rank>=10)?'Kartice se ob novih podatkih samodejno premaknejo. Razvrstitev ni ocena dobička.':'Trenutno ni kandidata za vstop. Program zbira podatke ali čaka na izpolnjene filtre.';
 for(const {c} of ranked){
 const d=document.createElement('details');d.dataset.id=c.id;d.open=expanded.has(c.id);const summary=document.createElement('summary'),sig=signal(c);summary.textContent=c.symbol+' · '+sig.name;d.append(summary);
 const add=text=>{const p=document.createElement('p');p.textContent=text;d.append(p);};
 add(sig.reason);add('Kovanec: '+c.token+' · par: '+c.id);add('Zadnji prejem: '+time(c.time)+' · '+Math.min(c.history.length,16)+'/16 potrebnih posnetkov.');
 add((fresh(c)?'Izpolnjeno: ':'Manjka: ')+'svež odgovor vira (manj kot 75 sekund). Dejanska zakasnitev ponudnika ni znana.');
 add((c.liquidity>=10000?'Izpolnjeno: ':'Manjka: ')+'vsaj 10.000 USD likvidnosti; trenutno '+money(c.liquidity)+'. Likvidnost pomeni sredstva v trgovalnem paru.');
 add((c.volume>0?'Izpolnjeno: ':'Manjka: ')+'pozitiven promet v zadnjih 5 minutah; trenutno '+money(c.volume)+'.');
 if(sig.checks){add('Podpora: '+money(sig.levels.support)+' · Odpor: '+money(sig.levels.resistance)+'. To sta najnižja in najvišja cena prvih desetih od zadnjih 16 posnetkov.');for(const group of sig.checks){const h=document.createElement('h3');h.textContent=group.name;d.append(h);for(const item of group.items)add((item.ok?'Izpolnjeno: ':'Manjka: ')+item.label);}}
 else add('Cenovnih vzorcev trenutno ne preverjamo: najprej morajo biti izpolnjeni zgornji filtri in zbranih 16 neprekinjenih posnetkov.');
 const open=trades.find(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&t.id===c.id);
 if(open)add(`Demo že odprt: ${open.reason}, ${time(open.opened)} (${open.automatic?'samodejno':'ročno'}). ${open.interrupted?'Spremljanje je bilo prekinjeno; izid v vrzeli je neznan.':'Čakamo na cilj ali mejo izgube.'}`);
 else if(!sig.signal)add('Brez demo vstopa: vzorec ali podatkovni pogoji še niso izpolnjeni.');
 else if(!$('#auto').checked)add('Vzorec je izpolnjen. Samodejni demo vstopi so izključeni; možen je ročni pregled na grafu.');
 else if(trades.filter(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&!t.practice).length>=5)add('Samodejni demo čaka: odprtih je že pet poslov.');
 else add('Pogoji za samodejni demo so izpolnjeni. Ponovno jih preverimo ob naslednjem prejemu podatkov.');
 const b=document.createElement('button');b.textContent='Poglej cenovni graf';b.onclick=()=>openBoardGraph(c.id);d.append(b);host.append(d);
 const state=chosen.find(x=>x.c.id===c.id);if(state){const card=document.createElement('article');const h=document.createElement('h3');h.textContent=c.symbol;card.append(h);const title=document.createElement('strong');title.textContent=state.title;card.append(title);const reason=document.createElement('p');reason.textContent=state.reason;card.append(reason);if(state.collect){const bar=document.createElement('progress');bar.max=16;bar.value=Math.min(c.history.length,16);bar.setAttribute('aria-label','Napredek zbiranja');card.append(bar);}const action=document.createElement('button');action.textContent=state.open?'Poglej demo posel':'Poglej graf';action.onclick=()=>{if(state.open)navigate('journal','live');else openBoardGraph(c.id);};card.append(action);const more=document.createElement('details');more.dataset.id='top-'+c.id;more.open=expanded.has(more.dataset.id);const label=document.createElement('summary');label.textContent='Podrobnosti';more.append(label);for(const child of d.children){if(child.tagName!=='SUMMARY'&&child.tagName!=='BUTTON')more.append(child.cloneNode(true));}card.append(more);columns.get(boardColumn(state)).append(card);}
 }
}

function cardState(c){
 const open=trades.find(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&t.id===c.id),sig=signal(c);
 if(open)return {rank:1000,open:true,title:'Demo odprt',reason:open.interrupted||!fresh(c)?'Podatki so bili prekinjeni. Preveri posel v dnevniku.':'Spremljam, ali cena doseže cilj ali mejo izgube.'};
 if(!fresh(c)||c.liquidity<10000||!c.liquidity||!(c.volume>0)||sig.name==='Premor')return {rank:0,title:!fresh(c)?'Čakam na sveže podatke':sig.name==='Premor'?'Prekinjeni podatki':'Brez signala',reason:!fresh(c)?'Vir ni poslal svežih podatkov. Vstop je ustavljen.':sig.name==='Premor'?'V cenah je vrzel. Čakam na neprekinjene podatke.':!c.liquidity||c.liquidity<10000?'Ni dovolj podatkov o likvidnosti ali je prenizka.':'V zadnjih petih minutah ni prometa.'};
 if(c.history.length<16)return {rank:1+c.history.length/16,collect:true,title:'Zbiram podatke',reason:'Pusti stran odprto. Še približno '+Math.ceil((16-c.history.length)*30/60)+' min ob rednem osveževanju.'};
 if(sig.signal){const full=trades.filter(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&!t.practice).length>=5;return {rank:100,title:'Vzorec zaznan',reason:!$('#auto').checked?'Samodejni demo je izklopljen. Na grafu lahko preveriš vstop.':full?'Čakam, da se sprosti eno od petih mest za demo.':'Ob naslednjih podatkih ponovno preverim pogoje za demo vstop.'};}
 const groups=sig.checks||[],best=[...groups].sort((a,b)=>b.items.filter(x=>x.ok).length/b.items.length-a.items.filter(x=>x.ok).length/a.items.length)[0];
 const bounce=groups.find(g=>g.name==='Odboj od podpore');const waitingBounce=bounce?.items[0].ok&&!bounce.items[1].ok;
 return {rank:10+(best?best.items.filter(x=>x.ok).length/best.items.length:0),title:waitingBounce?'Čakam na odboj':'Čakam na vzorec',reason:waitingBounce?'Cena je blizu podpore. Čakam, da ponovno zraste.':'Cena še ne izpolnjuje vseh pogojev. Za zdaj samo opazujem.'};
}

function boardColumn(state){return state.open?'Demo odprt':state.collect?'Zbiranje podatkov':state.rank===0?'Brez signala':'Čakanje na vstop';}
$('#boardFilter').onchange=()=>watching();
$('#boardMore').onclick=()=>{showAllColumns=!showAllColumns;$('#boardMore').textContent=showAllColumns?'Pokaži manj':'Pokaži več v vseh stolpcih';watching();};

$('#overview').onclick=()=>navigate('dashboard','live');
$('#period').onchange=dashboard;$('#quality').onchange=dashboard;$('#usdRate').oninput=dashboard;
function dashboard(){
 const rate=Number($('#usdRate').value),prices=new Map([...coins.values()].map(c=>[c.id,{price:c.price,fresh:fresh(c)}]));
 const o=overview(trades,{period:$('#period').value||'all',quality:$('#quality').value||'all',rate:rate>0?rate:null,prices});
 $('#excludedNote').textContent=o.excluded+' dogodkov izgube podatkov je ločenih od poslov in rezultatov. Običajne izgube ostajajo vključene.';$('#dashNet').textContent=signed(o.net)+' SOL';$('#dashNet').className=tone(o.net);$('#dashNet').setAttribute('aria-label',(o.net>0?'Dobiček ':o.net<0?'Izguba ':'Nevtralno ')+signed(o.net)+' SOL po stroških');$('#winFill').style.width=(o.success===null?0:o.success*100)+'%';$('#dashUsd').textContent=o.usd===null?'USD: znesek ni izračunan — vnesi tečaj spodaj.':'≈ '+money(o.usd)+' pri ročno vnesenem tečaju '+money(rate)+' / SOL';
 $('#dashSuccess').textContent=o.success===null?'Še ni podatkov':(o.success*100).toLocaleString('sl-SI',{maximumFractionDigits:1})+' %';
 $('#dashDenominator').textContent=o.closed.length?o.wins+' dobičkonosnih od '+o.closed.length+' zaključenih poslov':'Ni zaključenih živih demo poslov v tem obdobju.';$('#dashDenominator').textContent+=' · '+o.open.length+' odprtih ni v deležu, od tega '+o.marks.filter(m=>m.pnl===null).length+' z neznanim izidom. Dodatno '+o.excluded+' izločenih izgub podatkov; to ni uspešnost vseh poskusov.';
 $('#dashCounts').textContent=o.closed.length+' / '+o.open.length;$('#dashOutcomes').textContent=o.wins+' dobitkov · '+o.losses+' izgub · '+o.flat+' brez spremembe';
 $('#dashOpen').textContent=!o.open.length?'Ni odprtih poslov':o.unrealized===null?'Neznano — manjkajo sveže cene ali je spremljanje prekinjeno.':signed(o.unrealized)+' SOL (ocena)';
 $('#dashOpen').className=o.unrealized===null?'neutral':tone(o.unrealized);const positions=$('#dashPositions');positions.replaceChildren();for(const m of o.marks){const p=document.createElement('p');p.textContent=m.trade.symbol+' · '+(m.pnl===null?'Neznano — prekinjeno ali brez sveže cene':signed(m.pnl)+' SOL (odprto)');p.className=m.pnl===null?'neutral':tone(m.pnl);positions.append(p);const b=document.createElement('button');b.textContent=m.trade.interrupted?'Preglej prekinitev':'Preglej posel';b.onclick=()=>reviewTrade(m.trade.key);positions.append(b);}$('#dashActivity').textContent=(healthy&&Date.now()-last<75000?'VIR POVEZAN':'SPREMLJANJE V PREMORU')+' · '+[...coins.values()].filter(c=>fresh(c)).length+' kovancev s svežim prejemom · '+(last?'zadnji prejem '+time(last):'čakam na prvi prejem')+'. Samodejni demo: '+($('#auto').checked?'vključen':'izključen')+'.';
 const rows=$('#dashRecent');rows.replaceChildren();for(const t of [...o.closed].reverse().slice(0,5)){const row=document.createElement('div');row.className='tradeRow';const name=document.createElement('div');const title=document.createElement('strong');title.textContent=t.symbol;const when=document.createElement('small');when.textContent=time(t.closed);name.append(title);name.append(when);row.append(name);const outcome=document.createElement('small');outcome.textContent=(t.interrupted?'PO VRZELI · neprimerljivo z neprekinjenim izidom · ':'')+(t.outcome||'Zaključeno');row.append(outcome);const profit=document.createElement('div');profit.className='return '+tone(t.pnl);const sol=document.createElement('strong');sol.textContent=(t.pnl>0?'↑ Dobiček ':t.pnl<0?'↓ Izguba ':'• Nevtralno ')+signed(t.pnl)+' SOL';profit.append(sol);const pct=document.createElement('span');pct.className='returnTag';pct.textContent=returnText(t);profit.append(pct);row.append(profit);rows.append(row);}rows.className=o.closed.length?'':'empty';if(!o.closed.length)rows.textContent='Za izbrano obdobje še ni zaključenih živih demo poslov. Vaje so samo v dnevniku.';
 const svg=$('#dashCurve');svg.replaceChildren();if(o.curve.length){const values=[0,...o.curve.map(p=>p.pnl)],lo=Math.min(...values),hi=Math.max(...values),range=hi-lo||.001;const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',values.map((v,i)=>`${25+i/(values.length-1)*650},${195-(v-lo)/range*160}`).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke',o.net<0?'#ff858e':'#62e4b3');line.setAttribute('stroke-width','3');for(const v of [lo,0,hi]){const y=195-(v-lo)/range*160;const grid=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,x] of Object.entries({x1:25,x2:675,y1:y,y2:y,stroke:'#33465e','stroke-dasharray':'4 5'}))grid.setAttribute(k,x);svg.append(grid);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x','28');label.setAttribute('y',Math.max(16,y-6));label.setAttribute('fill','#a0b5d1');label.setAttribute('font-size','13');label.textContent=v.toFixed(4)+' SOL';svg.append(label);}svg.append(line);$('#curveNote').textContent='Od 0 do '+o.net.toFixed(6)+' SOL · vsak korak je zaključen posel v izbranem obdobju; razmiki ne predstavljajo časa.';}else $('#curveNote').textContent='Krivulja se pojavi po prvem zaključenem živem demo poslu.';
}

function tone(n){return n>0?'positive':n<0?'negative':'neutral';}
function signed(n){return (n>0?'+':'')+n.toFixed(6);}
function returnText(t){const p=netReturnPercent(t);return p===null?'Donos % ni znan (manjka vložek)':(p>0?'+':'')+p.toLocaleString('sl-SI',{maximumFractionDigits:2})+' % neto';}

function interruptTrade(t,reason){
 if(!t.interrupted){t.gaps=t.gaps||[];t.gaps.push({detectedAt:Date.now(),lastObserved:t.lastObserved||null,reason});}
 t.interrupted=true;
}
let reviewingKey=null,confirmingDelete=null;
function reviewTrade(key){reviewingKey=key;navigate('journal','live');$('#tradeReview').scrollIntoView?.({block:'nearest'});}
function renderReview(){
 const panel=$('#tradeReview');panel.replaceChildren();const t=trades.find(t=>t.key===reviewingKey);panel.hidden=!t;if(!t)return;
 const add=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;panel.append(e);return e;};
 addDeleteControl(t,panel);add('h3',t.symbol+' · '+(t.closed?'Zaključen demo':t.interrupted?'Prekinjeno spremljanje':'Odprti demo'));
 if(t.interrupted){add('p','Izguba podatkov – izid neznan. Ta zapis je samo dogodek; ne vpliva na P&L ali uspešnost. Zapiranje po novi ceni ni omogočeno.');add('small','Vstop '+time(t.opened)+' · cena '+money(t.entry));return;}
 if(t.interrupted)add('p','Med vrzeljo ne vemo, ali bi bil dosežen cilj ali meja izgube. Nova povezava te zgodovine ne more obnoviti. Spanje je le eden od možnih vzrokov.');
 for(const g of t.gaps||[])add('small','Zaznano '+time(g.detectedAt)+' · '+g.reason+(g.lastObserved?' · zadnji prejem pred vrzeljo '+time(g.lastObserved):''));
 if(t.interrupted&&!t.gaps?.length)add('small','Starejši zapis prekinitve: čas in vzrok nista bila shranjena.');
 if(t.closed){add('p','Ročni zaključek ostane v dnevniku skupaj z oznako prekinitve.');return;}
 const c=coins.get(t.id);add('p','Vstop '+money(t.entry)+' · cilj '+money(t.target)+' · meja izgube '+money(t.stop));
 if(fresh(c)){add('p','Nova opažena cena: '+money(c.price)+' · prejeto '+time(c.time));add('p','Če zdaj zaključiš demo: približno '+signed(result(t.entry,c.price,tradeSize(t)))+' SOL po stroških. To je izid ob sedanji ceni, ne rekonstruiran izstop v vrzeli.');}
 else add('p','Za ta isti trgovalni par še ni sveže cene. Počakaj na nov prejem; zaključek je začasno onemogočen.');
 const b=add('button','Zaključi demo po novi opaženi ceni');b.disabled=!fresh(c);b.onclick=()=>{const latest=coins.get(t.id);if(t.closed||!fresh(latest)){renderReview();return;}close(t,latest,t.interrupted?'Ročno po prekinitvi · zgodovina vrzeli neznana':'Ročni izstop');draw();};
}

function addDeleteControl(t,panel){const b=document.createElement('button');if(confirmingDelete===t.key){const p=document.createElement('p');p.textContent='Izbris izloči samo ta zapis. Obnoviš ga lahko pod Izbrisani zapisi.';panel.append(p);b.textContent='Potrdi izbris: '+t.symbol;b.onclick=()=>{t.deletedAt=Date.now();save();reviewingKey=null;confirmingDelete=null;draw();};const cancel=document.createElement('button');cancel.textContent='Prekliči';cancel.onclick=()=>{confirmingDelete=null;renderReview();};panel.append(cancel);}else{b.textContent='Izbriši ta zapis';b.onclick=()=>{confirmingDelete=t.key;renderReview();};}panel.append(b);}

function renderDeleted(){const root=$('#deletedRows');root.replaceChildren();for(const t of trades.filter(t=>t.deletedAt)){const p=document.createElement('p');p.textContent=t.symbol+' · izbrisano '+time(t.deletedAt);const b=document.createElement('button');b.textContent='Obnovi zapis';b.onclick=()=>{delete t.deletedAt;if(!t.closed)interruptTrade(t,'Obnovitev izbrisanega odprtega posla');save();draw();};p.append(b);root.append(p);}}

function renderEvents(){const host=$('#dataEvents');host.replaceChildren();const events=trades.filter(t=>t.interrupted&&!t.deletedAt&&!t.practice);$('#eventsCount').textContent='Izguba podatkov – izid neznan · '+events.length;for(const t of events){const p=document.createElement('p');p.textContent=t.symbol+' · vstop '+time(t.opened)+' · '+money(t.entry)+' · izid neznan';const b=document.createElement('button');b.textContent='Uredi / izbriši dogodek';b.onclick=()=>reviewTrade(t.key);p.append(b);host.append(p);}if(!events.length)host.textContent='Ni zabeleženih izgub podatkov.';}

function stakeLabels(){const text=stake.toLocaleString('sl-SI',{maximumSignificantDigits:21,useGrouping:false});$('#stakeBadge').textContent='Novi demo · '+text+' SOL';renderManual(current(),'#open','#liveManualState');renderManual(coins.get(boardSelected),'#boardManual','#boardManualState');$('#stakeInput').value=text;$('#stakeCurrent').textContent='Za nove posle: '+text+' SOL. Obstoječi vložki ostanejo enaki.';}
function setStake(value){const next=parseStake(value);if(next===null){$('#stakeMessage').textContent='Vnesi veljavno pozitivno število, na primer 0,2.';return;}stake=next;try{localStorage.setItem('solana-stake-v1',String(stake));$('#stakeMessage').textContent='Vložek shranjen.';}catch{$('#stakeMessage').textContent='Vložek velja v tej seji; shranjevanje ni uspelo.';}stakeLabels();}
$('#stakeSave').onclick=()=>setStake($('#stakeInput').value);$('#stakeSmall').onclick=()=>setStake('0.1');$('#stakeLarge').onclick=()=>setStake('0.2');stakeLabels();
function openBoardGraph(id){if(boardSelected!==id)$("#boardManualFeedback").textContent="";boardSelected=id;renderBoardGraph();$('#boardGraphPanel').hidden=false;}
$('#boardGraphClose').onclick=()=>{boardSelected=null;$('#boardGraphPanel').hidden=true;};
function manualBlock(c){if(!fresh(c)||!Number.isFinite(c?.price)||c.price<=0)return 'Ročni vstop čaka na svežo pozitivno ceno.';if(trades.some(t=>!t.deletedAt&&!t.interrupted&&!t.closed&&(t.id===c.id||t.token===c.token)))return 'Ta kovanec že ima odprt demo posel.';if(trades.filter(t=>!t.practice&&!t.deletedAt&&!t.interrupted&&!t.closed).length>=5)return 'Dosežena je meja petih odprtih poslov.';return '';}
function manualEntry(c,feedback){const blocked=manualBlock(c);if(blocked){$(feedback).textContent=blocked;draw();return false;}if(!enter(c,signal(c),false))return false;$(feedback).textContent='Ročni demo zabeležen za '+c.symbol+' · '+stake.toLocaleString('sl-SI')+' SOL. Cilj '+money(c.price*1.1)+' · meja izgube '+money(c.price*.95)+'.';draw();return true;}
function renderManual(c,button,state){$(button).textContent='Ročni demo vstop · '+stake.toLocaleString('sl-SI',{maximumSignificantDigits:21,useGrouping:false})+' SOL';$(button).disabled=!!manualBlock(c);$(state).textContent='Trenutna cena: '+money(c?.price)+' · '+(manualBlock(c)||'Na voljo · lastna odločitev, tudi brez signala.');}
$('#boardManual').onclick=()=>manualEntry(coins.get(boardSelected),'#boardManualFeedback');

function renderBoardGraph(){
 const c=coins.get(boardSelected);if(!c)return;const sig=signal(c),analysis=fresh(c)?pattern(c.history):sig;
 $('#boardGraphName').textContent=c.symbol+' · cenovni posnetki';$('#boardGraphReason').textContent='Bot: '+sig.name+' · '+sig.reason;
 $('#boardGraphNote').textContent='Prejeto '+time(c.time)+' · zelena črta: opažena cena (USD), vodoravna os: čas. To niso borzne sveče. Ravni pojasnjujejo ZADNJI izračun; niso prihodnje fiksno naročilo. Ob novem posnetku se okno in predhodna cena premakneta. Sam dotik ravni ne zagotovi vstopa.';
 chart(c.history,analysis.levels,'#boardChart');const host=$('#boardConditions');host.replaceChildren();const add=(text,color)=>{const el=document.createElement('p');el.textContent=text;if(color)el.style.color=color;host.append(el);};
 if(analysis.levels){const l=analysis.levels;add('Podpora '+money(l.support)+' · območje dotika ±2 %: '+money(l.support*.98)+'–'+money(l.support*1.02),'#edc687');add('Odpor '+money(l.resistance)+' · retest območje −1 % do +2 %: '+money(l.resistance*.99)+'–'+money(l.resistance*1.02),'#bba7f8');add('Modra črtkana: zadnja cena mora biti > '+money(l.retest)+' (predhodna cena × 1,01; preboj/retest ali višje dno).','#60a5fa');add('Oranžna črtkana: zadnja cena mora biti > '+money(l.bounce)+' (predhodna cena × 1,015; odboj).','#fb923c');for(const group of analysis.checks){add(group.name+': '+(group.items.every(i=>i.ok)?'vzorec izpolnjen':'še čaka'));for(const item of group.items)add((item.ok?'✓ ':'Čaka: ')+item.label);}}
 else add(analysis.reason+' Nakupna raven še ni na voljo.');
 add('Dodatni pogoji bota: '+(c.liquidity>=10000?'✓':'manjka')+' likvidnost ≥ 10.000 USD; '+(c.volume>0?'✓':'manjka')+' pozitiven 5-min promet; '+(fresh(c)?'✓':'manjka')+' sveža cena. Samodejni vstopi: '+($('#auto').checked?'vključeni':'izključeni')+'. Veljajo tudi omejitev petih poslov, en odprt posel na kovanec in enkratna obdelava signala.');
 renderManual(c,'#boardManual','#boardManualState');
}
